-- Rename listenbrainz_explore to listenbrainz_fresh_releases and add new weekly types
-- This migration modifies the SubscriptionType enum

-- First, add the new enum values
ALTER TABLE `Subscription` MODIFY COLUMN `type` ENUM(
  'lastfm_chart',
  'lastfm_tag',
  'lastfm_geo',
  'lastfm_library',
  'lastfm_similar',
  'musicbrainz',
  'musicbrainz_new',
  'combined',
  'spotify_playlist',
  'spotify_new_releases',
  'spotify_followed',
  'spotify_saved_albums',
  'spotify_liked_songs',
  'spotify_discover_weekly',
  'spotify_release_radar',
  'spotify_daily_mix',
  'spotify_on_repeat',
  'spotify_featured',
  'spotify_category',
  'spotify_library',
  'spotify_public_playlist',
  'ai_recommendation',
  'tautulli_similar',
  'deezer_favorites',
  'deezer_playlists',
  'deezer_playlist',
  'deezer_flow',
  'deezer_chart',
  'deezer_history',
  'deezer_genre',
  'deezer_search',
  'tidal_favorites',
  'tidal_followed_artists',
  'tidal_playlists',
  'tidal_playlist',
  'tidal_discovery',
  'tidal_new_arrivals',
  'tidal_mix',
  'listenbrainz_top',
  'listenbrainz_similar',
  'listenbrainz_recommendations',
  'listenbrainz_explore',
  'listenbrainz_fresh_releases',
  'listenbrainz_weekly_jams',
  'listenbrainz_weekly_exploration',
  'listenbrainz_year',
  'listenbrainz_playlist',
  'listenbrainz_radio',
  'listenbrainz_loved',
  'discogs_label',
  'discogs_style',
  'bandcamp_tag',
  'bandcamp_new'
) NOT NULL;

-- Migrate any existing listenbrainz_explore subscriptions to listenbrainz_fresh_releases
UPDATE `Subscription` SET `type` = 'listenbrainz_fresh_releases' WHERE `type` = 'listenbrainz_explore';

-- Now remove the old listenbrainz_explore value from the enum
ALTER TABLE `Subscription` MODIFY COLUMN `type` ENUM(
  'lastfm_chart',
  'lastfm_tag',
  'lastfm_geo',
  'lastfm_library',
  'lastfm_similar',
  'musicbrainz',
  'musicbrainz_new',
  'combined',
  'spotify_playlist',
  'spotify_new_releases',
  'spotify_followed',
  'spotify_saved_albums',
  'spotify_liked_songs',
  'spotify_discover_weekly',
  'spotify_release_radar',
  'spotify_daily_mix',
  'spotify_on_repeat',
  'spotify_featured',
  'spotify_category',
  'spotify_library',
  'spotify_public_playlist',
  'ai_recommendation',
  'tautulli_similar',
  'deezer_favorites',
  'deezer_playlists',
  'deezer_playlist',
  'deezer_flow',
  'deezer_chart',
  'deezer_history',
  'deezer_genre',
  'deezer_search',
  'tidal_favorites',
  'tidal_followed_artists',
  'tidal_playlists',
  'tidal_playlist',
  'tidal_discovery',
  'tidal_new_arrivals',
  'tidal_mix',
  'listenbrainz_top',
  'listenbrainz_similar',
  'listenbrainz_recommendations',
  'listenbrainz_fresh_releases',
  'listenbrainz_weekly_jams',
  'listenbrainz_weekly_exploration',
  'listenbrainz_year',
  'listenbrainz_playlist',
  'listenbrainz_radio',
  'listenbrainz_loved',
  'discogs_label',
  'discogs_style',
  'bandcamp_tag',
  'bandcamp_new'
) NOT NULL;
